### ISSUE TITLE
How to skip header on csv files? 

### ISSUE THREAD

**Issue by babaganoush** [goodby/csv#15]
Hello,

I can do something like 

if $row[16] == "name"
{
return;
}

however was wondering if there was a way to set a skip option in config so it can skip x number of lines 

thanks again for an awesome library

**Comment by emilv** [comment]
For anyone finding this issue through search engines: Since version 1.1.0 (released November 2013) you can skip the first line with `$config->setIgnoreHeaderLine(true);`
