### ISSUE TITLE
PHP 5.6 compatible

### ISSUE THREAD

**Issue by zulus** [goodby/csv#60]
I see this error in my symfony logs (PHP 5.6.6):

Runtime Notice: Declaration of Goodby\CSV\Export\Standard\CsvFileObject::fputcsv() should be compatible with SplFileObject::fputcsv($fields, $delimiter = NULL, $enclosure = NULL, $escape = NULL)" at /Users/zulus/www/mb/vendor/goodby/csv/src/Goodby/CSV/Export/Standard/CsvFileObject.php

**Comment by rms2219** [comment]
+1 - This is an issue on PHP >= 5.5.21 & >= 5.6.5. We need a new release tagged so that the fix you have in master could be used.

**Comment by jewome62** [comment]
+1

**Comment by auss** [comment]
+1

**Comment by krecik** [comment]
+1

**Comment by wadziu** [comment]
+1

**Comment by adismsc** [comment]
+1

**Comment by skoszuta** [comment]
+1

**Comment by codeator** [comment]
+1

**Comment by mguillermin** [comment]
+1

**Comment by panique** [comment]
+1

**Comment by panique** [comment]
Quick fix: Change the line in your composer.json from

```
"goodby/csv": "*"
```
to
```
"goodby/csv": "dev-master"
```
and do a `composer update`. This fix was kindly supported by Captain Obvious.

**Comment by jewome62** [comment]
Is not good to use branch's name in composer.json because update your composer to 1 year and you break your app.

I recommand to use : 
``
"goodby/csv": "dev-master#b289ca3e3f6ad3c76b7d8c3bef3effd0232ca13a"
``

For not update with break version

**Comment by boundaryfunctions** [comment]
+1

This still hasn't been fixed, but it works without problems with the revision in `master`.

**Comment by micayael** [comment]
Are you planning to create a 0.1.1 tag for this?

**Comment by micayael** [comment]
Is there a new tag to fix this?

**Comment by jjeaton** [comment]
+1

**Comment by calmdev** [comment]
I just ran into this myself.

**Comment by reoring** [comment]
fixed
