### ISSUE TITLE
ob_start

### ISSUE THREAD

**Issue by FadelChafai** [goodby/csv#61]
I'm using Zend Framework 1.12, to export large files I was forced  in my view helper to use ob_start() before calling $exporter->export  if not the script spends so much time before sending me the file

```
....
        ob_start();

        header("Content-Type: application/octet-stream");
        header('Content-Disposition: attachment; filename='.$filename.'.csv');

        $exporter->export('php://output', new \PdoCollection($row));

        ob_end_flush();
.....
```

**Comment by reoring** [comment]
Should not use ob_start
